begin;

create table if not exists public.user_settings (
  discord_id text primary key,
  nickname text not null default '',
  about_me text not null default '',
  personality text not null default 'prisma_default',
  humor_level integer not null default 1 check (humor_level between 1 and 5),
  allow_mentions boolean not null default true,
  memory_enabled boolean not null default true,
  spontaneous_interactions boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.prisma_operator_rules (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  rule text not null check (char_length(rule) between 5 and 350),
  created_at timestamptz not null default now(),
  unique (owner_id, rule)
);

create table if not exists public.prisma_self_learnings (
  id bigint generated by default as identity primary key,
  learning_key text not null unique check (learning_key ~ '^[a-z0-9_]{3,80}$'),
  category text not null,
  insight text not null check (char_length(insight) between 20 and 300),
  confidence smallint not null default 50 check (confidence between 0 and 100),
  evidence_count integer not null default 1 check (evidence_count >= 1),
  status text not null default 'candidate' check (status in ('candidate', 'active', 'rejected')),
  first_observed_at timestamptz not null default now(),
  last_observed_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.prisma_self_learnings drop constraint if exists prisma_self_learnings_category_check;
alter table public.prisma_self_learnings drop constraint if exists prisma_self_learnings_category_allowed;
alter table public.prisma_self_learnings add constraint prisma_self_learnings_category_allowed
  check (category in ('conversation_style','language_pattern','tone_strategy','interaction_pattern','response_strategy','recurring_topic','topic_affinity','self_correction'));
create index if not exists prisma_self_learnings_status_confidence_idx on public.prisma_self_learnings (status, confidence desc);

-- Garante compatibilidade ao reaplicar o schema sobre instalações anteriores.
alter table public.user_settings
  add column if not exists about_me text not null default '';
alter table public.user_settings drop constraint if exists user_settings_about_me_length;
alter table public.user_settings
  add constraint user_settings_about_me_length check (char_length(about_me) <= 300);

update public.prisma_operator_rules
set rule = left(rule, 350)
where char_length(rule) > 350;
alter table public.prisma_operator_rules drop constraint if exists prisma_operator_rules_rule_check;
alter table public.prisma_operator_rules
  add constraint prisma_operator_rules_rule_check check (char_length(rule) between 5 and 350);

-- personality e humor_level permanecem temporariamente apenas para compatibilidade
-- com deploys antigos. O fluxo adaptativo não lê nem grava essas colunas.

create table if not exists public.prisma_relationships (
  discord_id text primary key,
  familiarity smallint not null default 0 check (familiarity between 0 and 100),
  warmth smallint not null default 0 check (warmth between 0 and 100),
  patience smallint not null default 0 check (patience between 0 and 100),
  banter smallint not null default 0 check (banter between 0 and 100),
  trust smallint not null default 0 check (trust between 0 and 100),
  relationship_summary text check (char_length(relationship_summary) <= 300),
  recent_milestones jsonb not null default '[]'::jsonb check (jsonb_typeof(recent_milestones) = 'array' and jsonb_array_length(recent_milestones) <= 5),
  interaction_count integer not null default 0 check (interaction_count >= 0),
  summary_updated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.prisma_temperament (
  discord_id text primary key,
  mood text not null default 'neutral' check (mood in ('neutral', 'playful', 'warm', 'calm', 'serious', 'energetic', 'annoyed')),
  energy smallint not null default 60 check (energy between 0 and 100),
  sarcasm smallint not null default 35 check (sarcasm between 0 and 100),
  affection smallint not null default 50 check (affection between 0 and 100),
  last_interaction_at timestamptz,
  updated_at timestamptz not null default now()
);

-- Torna o bootstrap seguro para bancos onde uma versao anterior criou apenas
-- parte das tabelas adaptativas. Colunas obrigatorias recebem valores validos
-- antes de os NOT NULL e CHECKs serem (re)aplicados.
alter table public.prisma_relationships
  add column if not exists discord_id text,
  add column if not exists familiarity smallint not null default 0,
  add column if not exists warmth smallint not null default 0,
  add column if not exists patience smallint not null default 0,
  add column if not exists banter smallint not null default 0,
  add column if not exists trust smallint not null default 0,
  add column if not exists relationship_summary text,
  add column if not exists recent_milestones jsonb not null default '[]'::jsonb,
  add column if not exists interaction_count integer not null default 0,
  add column if not exists summary_updated_at timestamptz,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

update public.prisma_relationships
set familiarity = greatest(0, least(100, coalesce(familiarity, 10))),
    warmth = greatest(0, least(100, coalesce(warmth, 50))),
    patience = greatest(0, least(100, coalesce(patience, 60))),
    banter = greatest(0, least(100, coalesce(banter, 30))),
    trust = greatest(0, least(100, coalesce(trust, 0))),
    relationship_summary = left(relationship_summary, 300),
    interaction_count = greatest(0, coalesce(interaction_count, 0)),
    created_at = coalesce(created_at, now()),
    updated_at = coalesce(updated_at, now());

alter table public.prisma_relationships
  alter column familiarity set default 0,
  alter column familiarity set not null,
  alter column warmth set default 0,
  alter column warmth set not null,
  alter column patience set default 0,
  alter column patience set not null,
  alter column banter set default 0,
  alter column banter set not null,
  alter column trust set default 0,
  alter column trust set not null,
  alter column interaction_count set default 0,
  alter column interaction_count set not null,
  alter column created_at set default now(),
  alter column created_at set not null,
  alter column updated_at set default now(),
  alter column updated_at set not null;

alter table public.prisma_relationships drop constraint if exists prisma_relationships_familiarity_check;
alter table public.prisma_relationships add constraint prisma_relationships_familiarity_check check (familiarity between 0 and 100);
alter table public.prisma_relationships drop constraint if exists prisma_relationships_warmth_check;
alter table public.prisma_relationships add constraint prisma_relationships_warmth_check check (warmth between 0 and 100);
alter table public.prisma_relationships drop constraint if exists prisma_relationships_patience_check;
alter table public.prisma_relationships add constraint prisma_relationships_patience_check check (patience between 0 and 100);
alter table public.prisma_relationships drop constraint if exists prisma_relationships_banter_check;
alter table public.prisma_relationships add constraint prisma_relationships_banter_check check (banter between 0 and 100);
alter table public.prisma_relationships drop constraint if exists prisma_relationships_trust_check;
alter table public.prisma_relationships add constraint prisma_relationships_trust_check check (trust between 0 and 100);
alter table public.prisma_relationships drop constraint if exists prisma_relationships_relationship_summary_check;
alter table public.prisma_relationships add constraint prisma_relationships_relationship_summary_check check (char_length(relationship_summary) <= 300);
alter table public.prisma_relationships drop constraint if exists prisma_relationships_interaction_count_check;
alter table public.prisma_relationships add constraint prisma_relationships_interaction_count_check check (interaction_count >= 0);

alter table public.prisma_temperament
  add column if not exists discord_id text,
  add column if not exists mood text not null default 'neutral',
  add column if not exists energy smallint not null default 60,
  add column if not exists sarcasm smallint not null default 35,
  add column if not exists affection smallint not null default 50,
  add column if not exists last_interaction_at timestamptz,
  add column if not exists updated_at timestamptz not null default now();

update public.prisma_temperament
set mood = case
      when mood in ('neutral', 'playful', 'warm', 'calm', 'serious', 'energetic', 'annoyed') then mood
      else 'neutral'
    end,
    energy = greatest(0, least(100, coalesce(energy, 60))),
    sarcasm = greatest(0, least(100, coalesce(sarcasm, 35))),
    affection = greatest(0, least(100, coalesce(affection, 50))),
    updated_at = coalesce(updated_at, now());

alter table public.prisma_temperament
  alter column mood set default 'neutral',
  alter column mood set not null,
  alter column energy set default 60,
  alter column energy set not null,
  alter column sarcasm set default 35,
  alter column sarcasm set not null,
  alter column affection set default 50,
  alter column affection set not null,
  alter column updated_at set default now(),
  alter column updated_at set not null;

alter table public.prisma_temperament drop constraint if exists prisma_temperament_mood_check;
alter table public.prisma_temperament add constraint prisma_temperament_mood_check check (mood in ('neutral', 'playful', 'warm', 'calm', 'serious', 'energetic', 'annoyed'));
alter table public.prisma_temperament drop constraint if exists prisma_temperament_energy_check;
alter table public.prisma_temperament add constraint prisma_temperament_energy_check check (energy between 0 and 100);
alter table public.prisma_temperament drop constraint if exists prisma_temperament_sarcasm_check;
alter table public.prisma_temperament add constraint prisma_temperament_sarcasm_check check (sarcasm between 0 and 100);
alter table public.prisma_temperament drop constraint if exists prisma_temperament_affection_check;
alter table public.prisma_temperament add constraint prisma_temperament_affection_check check (affection between 0 and 100);

do $adaptive_schema$
begin
  if not exists (select 1 from public.prisma_relationships where discord_id is null) then
    alter table public.prisma_relationships alter column discord_id set not null;
  end if;
  if not exists (select 1 from public.prisma_temperament where discord_id is null) then
    alter table public.prisma_temperament alter column discord_id set not null;
  end if;
end
$adaptive_schema$;

do $adaptive_unique_keys$
begin
  if not exists (
    select 1
    from pg_catalog.pg_constraint c
    join pg_catalog.pg_attribute a
      on a.attrelid = c.conrelid and a.attname = 'discord_id'
    where c.conrelid = 'public.prisma_relationships'::pg_catalog.regclass
      and c.contype in ('p', 'u')
      and pg_catalog.array_length(c.conkey, 1) = 1
      and c.conkey[1] = a.attnum
  ) then
    create unique index if not exists prisma_relationships_discord_id_uidx
      on public.prisma_relationships (discord_id);
  end if;

  if not exists (
    select 1
    from pg_catalog.pg_constraint c
    join pg_catalog.pg_attribute a
      on a.attrelid = c.conrelid and a.attname = 'discord_id'
    where c.conrelid = 'public.prisma_temperament'::pg_catalog.regclass
      and c.contype in ('p', 'u')
      and pg_catalog.array_length(c.conkey, 1) = 1
      and c.conkey[1] = a.attnum
  ) then
    create unique index if not exists prisma_temperament_discord_id_uidx
      on public.prisma_temperament (discord_id);
  end if;
end
$adaptive_unique_keys$;

create table if not exists public.ai_usage (
  id bigint generated by default as identity primary key,
  discord_id text not null,
  model text not null,
  input_tokens integer not null default 0,
  output_tokens integer not null default 0,
  total_tokens integer not null default 0,
  estimated_cost_usd numeric(14,8) not null default 0,
  estimated_cost_brl numeric(14,8) not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists ai_usage_created_idx on public.ai_usage (created_at);

create table if not exists public.ai_events (
  id bigint generated by default as identity primary key,
  discord_id text not null,
  interaction_type text not null default 'spontaneous',
  created_at timestamptz not null default now()
);
create index if not exists ai_events_user_created_idx on public.ai_events (discord_id, created_at desc);

create table if not exists public.prisma_user_profiles (
  user_id text primary key,
  display_name text,
  profile_summary text,
  communication_style text,
  first_interaction_at timestamptz not null default now(),
  last_interaction_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists prisma_user_profiles_last_interaction_idx on public.prisma_user_profiles (last_interaction_at desc);

create table if not exists public.prisma_memories (
  id bigint generated by default as identity primary key,
  user_id text not null,
  memory_key text,
  memory_type text not null,
  content text not null check (char_length(content) between 3 and 300),
  importance smallint not null default 50 check (importance between 0 and 100),
  confidence smallint not null default 60 check (confidence between 0 and 100),
  source_message_id text,
  occurrence_count integer not null default 1 check (occurrence_count >= 1),
  last_seen_at timestamptz not null default now(),
  status text not null default 'active' check (status in ('active','superseded','forgotten')),
  superseded_by bigint references public.prisma_memories(id) on delete set null,
  valid_until timestamptz,
  last_confirmed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.prisma_memories drop constraint if exists prisma_memories_memory_type_check;
alter table public.prisma_memories drop constraint if exists prisma_memories_memory_type_allowed;
alter table public.prisma_memories add constraint prisma_memories_memory_type_allowed
  check (memory_type in ('preference','interest','media','game','hobby','project','goal','event','achievement','routine','communication','social','inside_joke','relationship'));
alter table public.prisma_memories
  add column if not exists memory_key text,
  add column if not exists occurrence_count integer not null default 1,
  add column if not exists last_seen_at timestamptz not null default now(),
  add column if not exists status text not null default 'active',
  add column if not exists superseded_by bigint references public.prisma_memories(id) on delete set null,
  add column if not exists valid_until timestamptz,
  add column if not exists last_confirmed_at timestamptz not null default now();
alter table public.prisma_memories drop constraint if exists prisma_memories_occurrence_count_check;
alter table public.prisma_memories
  add constraint prisma_memories_occurrence_count_check check (occurrence_count >= 1);
alter table public.prisma_memories drop constraint if exists prisma_memories_status_check;
alter table public.prisma_memories
  add constraint prisma_memories_status_check check (status in ('active','superseded','forgotten'));
create index if not exists prisma_memories_user_idx on public.prisma_memories (user_id, updated_at desc);
create index if not exists prisma_memories_user_type_idx on public.prisma_memories (user_id, memory_type);
drop index if exists public.prisma_memories_user_content_uidx;
drop index if exists public.prisma_memories_user_key_uidx;
create unique index if not exists prisma_memories_active_user_content_uidx on public.prisma_memories (user_id, lower(content)) where status = 'active';
create unique index if not exists prisma_memories_active_user_key_uidx on public.prisma_memories (user_id, memory_key) where memory_key is not null and status = 'active';
create index if not exists prisma_memories_user_status_idx on public.prisma_memories (user_id, status, updated_at desc);
create index if not exists prisma_memories_active_valid_until_idx on public.prisma_memories (valid_until) where status = 'active' and valid_until is not null;
create index if not exists prisma_memories_historical_retention_idx on public.prisma_memories (status, updated_at) where status in ('superseded','forgotten');

create or replace function public.set_prisma_memory_valid_until()
returns trigger
language plpgsql
set search_path = pg_catalog
as $set_prisma_memory_valid_until$
begin
  if new.valid_until is null then new.valid_until := now() + interval '180 days'; end if;
  new.valid_until := least(new.valid_until, now() + interval '180 days');
  if new.last_confirmed_at is null then new.last_confirmed_at := now(); end if;
  return new;
end
$set_prisma_memory_valid_until$;
drop trigger if exists prisma_memories_default_validity on public.prisma_memories;
create trigger prisma_memories_default_validity
before insert or update of memory_type, valid_until, last_confirmed_at on public.prisma_memories
for each row execute function public.set_prisma_memory_valid_until();
update public.prisma_memories
set valid_until = now() + interval '180 days'
where status = 'active' and valid_until is null;
revoke all on function public.set_prisma_memory_valid_until() from public, anon, authenticated;
grant execute on function public.set_prisma_memory_valid_until() to service_role;

create or replace function public.enforce_prisma_memory_limit(p_user_id text, p_limit integer default 300)
returns integer
language plpgsql
security definer
set search_path = pg_catalog
as $enforce_prisma_memory_limit$
declare
  v_changed integer := 0;
  v_limit integer := greatest(1, least(coalesce(p_limit, 300), 300));
begin
  update public.prisma_memories
  set status = 'forgotten', updated_at = now()
  where user_id = p_user_id and status = 'active'
    and valid_until is not null and valid_until <= now();

  with ranked as (
    select id, row_number() over (
      order by importance desc, confidence desc, occurrence_count desc,
        last_confirmed_at desc nulls last, updated_at desc
    ) as position
    from public.prisma_memories
    where user_id = p_user_id and status = 'active'
  )
  update public.prisma_memories m
  set status = 'forgotten', updated_at = now()
  from ranked r
  where m.id = r.id and r.position > v_limit;
  get diagnostics v_changed = row_count;
  return v_changed;
end
$enforce_prisma_memory_limit$;

revoke all on function public.enforce_prisma_memory_limit(text, integer) from public, anon, authenticated;
grant execute on function public.enforce_prisma_memory_limit(text, integer) to service_role;

create table if not exists public.prisma_messages (
  id bigint generated by default as identity primary key,
  message_id text not null unique,
  guild_id text not null,
  channel_id text not null,
  user_id text not null,
  content text not null,
  author_is_prisma boolean not null default false,
  reply_to_message_id text,
  created_at timestamptz not null default now()
);
create index if not exists prisma_messages_user_created_idx on public.prisma_messages (user_id, created_at desc);
create index if not exists prisma_messages_channel_created_idx on public.prisma_messages (channel_id, created_at desc);
create index if not exists prisma_messages_created_idx on public.prisma_messages (created_at);

alter table public.prisma_user_profiles
  add column if not exists guild_id text,
  add column if not exists created_at timestamptz not null default now();
do $migrate_profile_arrays$
begin
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'prisma_user_profiles' and column_name = 'interests') then
    execute $sql$
      insert into public.prisma_memories (user_id, memory_key, memory_type, content, importance, confidence)
      select p.user_id, 'legacy-interest:' || md5(i.value), 'interest', left('Gosta de ' || i.value || '.', 300), 50, 60
      from public.prisma_user_profiles p cross join lateral jsonb_array_elements_text(p.interests) as i(value)
      where char_length(trim(i.value)) between 3 and 280 on conflict do nothing
    $sql$;
  end if;
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'prisma_user_profiles' and column_name = 'known_preferences') then
    execute $sql$
      insert into public.prisma_memories (user_id, memory_key, memory_type, content, importance, confidence)
      select p.user_id, 'legacy-preference:' || md5(pref.value), 'preference', left(pref.value, 300), 50, 60
      from public.prisma_user_profiles p cross join lateral jsonb_array_elements_text(p.known_preferences) as pref(value)
      where char_length(trim(pref.value)) between 3 and 300 on conflict do nothing
    $sql$;
  end if;
end
$migrate_profile_arrays$;
alter table public.prisma_user_profiles
  drop column if exists interests,
  drop column if exists known_preferences;

create table if not exists public.prisma_daily_summaries (
  id bigint generated by default as identity primary key,
  user_id text not null,
  summary_date date not null,
  summary text not null check (char_length(summary) between 3 and 1200),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, summary_date)
);
create index if not exists prisma_daily_summaries_user_date_idx on public.prisma_daily_summaries (user_id, summary_date desc);

create table if not exists public.prisma_period_summaries (
  id bigint generated by default as identity primary key,
  user_id text not null,
  period_type text not null check (period_type in ('weekly','monthly')),
  period_start date not null,
  period_end date not null,
  summary text not null check (char_length(summary) between 3 and 8000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, period_type, period_start),
  check (period_end >= period_start)
);
create index if not exists prisma_period_summaries_user_end_idx on public.prisma_period_summaries (user_id, period_end desc);
create index if not exists prisma_period_summaries_type_end_idx on public.prisma_period_summaries (period_type, period_end);

create table if not exists public.prisma_emotional_states (
  user_id text primary key,
  mood text not null default 'neutral' check (mood in ('neutral', 'playful', 'warm', 'calm', 'serious', 'energetic', 'annoyed')),
  happiness smallint not null default 0 check (happiness between 0 and 100),
  sadness smallint not null default 0 check (sadness between 0 and 100),
  anger smallint not null default 0 check (anger between 0 and 100),
  irritation smallint not null default 0 check (irritation between 0 and 100),
  affection smallint not null default 0 check (affection between 0 and 100),
  curiosity smallint not null default 0 check (curiosity between 0 and 100),
  excitement smallint not null default 0 check (excitement between 0 and 100),
  boredom smallint not null default 0 check (boredom between 0 and 100),
  confidence smallint not null default 0 check (confidence between 0 and 100),
  energy smallint not null default 0 check (energy between 0 and 100),
  sarcasm smallint not null default 0 check (sarcasm between 0 and 100),
  last_interaction_at timestamptz,
  updated_at timestamptz not null default now()
);
alter table public.prisma_emotional_states
  add column if not exists mood text not null default 'neutral',
  add column if not exists sarcasm smallint not null default 0,
  add column if not exists last_interaction_at timestamptz;
alter table public.prisma_emotional_states drop constraint if exists prisma_emotional_states_mood_check;
alter table public.prisma_emotional_states
  add constraint prisma_emotional_states_mood_check check (mood in ('neutral', 'playful', 'warm', 'calm', 'serious', 'energetic', 'annoyed'));
alter table public.prisma_emotional_states drop constraint if exists prisma_emotional_states_sarcasm_check;
alter table public.prisma_emotional_states
  add constraint prisma_emotional_states_sarcasm_check check (sarcasm between 0 and 100);

-- Publicações da galeria. Curtidas e comentários ficam no próprio post porque
-- o módulo atual persiste esses dados como arrays JSON.
create table if not exists public.gallery_posts (
  message_id text primary key,
  owner_id text not null,
  likes jsonb not null default '[]'::jsonb,
  comments jsonb not null default '[]'::jsonb,
  instagram_handle text,
  report_pending boolean not null default false,
  report_disabled boolean not null default false,
  updated_at timestamptz not null default now(),
  constraint gallery_posts_likes_array check (jsonb_typeof(likes) = 'array'),
  constraint gallery_posts_comments_array check (jsonb_typeof(comments) = 'array')
);

alter table public.gallery_posts
  add column if not exists comments jsonb not null default '[]'::jsonb,
  add column if not exists instagram_handle text,
  add column if not exists report_pending boolean not null default false,
  add column if not exists report_disabled boolean not null default false;
alter table public.gallery_posts drop constraint if exists gallery_posts_likes_array;
alter table public.gallery_posts
  add constraint gallery_posts_likes_array check (jsonb_typeof(likes) = 'array');
alter table public.gallery_posts drop constraint if exists gallery_posts_comments_array;
alter table public.gallery_posts
  add constraint gallery_posts_comments_array check (jsonb_typeof(comments) = 'array');
create index if not exists gallery_posts_owner_idx on public.gallery_posts (owner_id);

-- Sessões do sistema de procura de grupos (LFG).
create table if not exists public.lfg_sessions (
  id uuid primary key,
  guild_id text not null,
  channel_id text not null,
  message_id text,
  role_mention_message_id text,
  creator_id text not null,
  game text not null check (game in ('fortnite', 'valorant', 'roblox', 'overwatch', 'league_of_legends', 'minecraft', 'marvel_rivals', 'dead_by_daylight')),
  max_players smallint not null check (max_players between 2 and 12),
  participants jsonb not null default '[]'::jsonb check (jsonb_typeof(participants) = 'array'),
  note text not null default '' check (char_length(note) <= 500),
  auto_voice_enabled boolean not null default false,
  voice_channel_id text,
  temporary_role_id text,
  status text not null default 'open' check (status in ('open', 'completed', 'closed', 'expired', 'deleted')),
  delete_voice_when_empty boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  expires_at timestamptz not null
);
create index if not exists lfg_sessions_guild_status_idx on public.lfg_sessions (guild_id, status);
create index if not exists lfg_sessions_creator_status_idx on public.lfg_sessions (creator_id, status);
create index if not exists lfg_sessions_expires_idx on public.lfg_sessions (expires_at);

-- Migração compatível para instalações que usavam os nomes e a escala antigos.
update public.user_settings set personality = case personality
  when 'padrao' then 'prisma_default'
  when 'sarcastico' then 'sarcastic'
  when 'fofo' then 'cute'
  when 'caotico' then 'chaotic'
  else personality
end;
alter table public.user_settings alter column personality set default 'prisma_default';
alter table public.user_settings drop constraint if exists user_settings_humor_level_check;
update public.user_settings set humor_level = greatest(1, least(5, humor_level));
alter table public.user_settings add constraint user_settings_humor_level_check check (humor_level between 1 and 5);
alter table public.user_settings alter column humor_level set default 1;

alter table public.user_settings enable row level security;
alter table public.prisma_operator_rules enable row level security;
alter table public.prisma_self_learnings enable row level security;
alter table public.ai_usage enable row level security;
alter table public.ai_events enable row level security;
alter table public.prisma_relationships enable row level security;
alter table public.prisma_temperament enable row level security;
alter table public.prisma_user_profiles enable row level security;
alter table public.prisma_memories enable row level security;
alter table public.prisma_messages enable row level security;
alter table public.prisma_daily_summaries enable row level security;
alter table public.prisma_period_summaries enable row level security;
alter table public.prisma_emotional_states enable row level security;
alter table public.gallery_posts enable row level security;
alter table public.lfg_sessions enable row level security;

-- O bot usa exclusivamente a chave service_role no backend. Não há políticas
-- para clientes públicos, e estas revogações deixam essa intenção explícita.
revoke all on table public.user_settings, public.prisma_operator_rules,
  public.prisma_relationships, public.prisma_temperament, public.prisma_self_learnings,
  public.ai_usage, public.ai_events,
  public.prisma_user_profiles, public.prisma_memories, public.prisma_messages,
  public.prisma_daily_summaries, public.prisma_period_summaries, public.prisma_emotional_states,
  public.gallery_posts, public.lfg_sessions from anon, authenticated;
grant all on table public.user_settings, public.prisma_operator_rules,
  public.prisma_relationships, public.prisma_temperament, public.prisma_self_learnings,
  public.ai_usage, public.ai_events,
  public.prisma_user_profiles, public.prisma_memories, public.prisma_messages,
  public.prisma_daily_summaries, public.prisma_period_summaries, public.prisma_emotional_states,
  public.gallery_posts, public.lfg_sessions to service_role;
grant usage, select on all sequences in schema public to service_role;

drop function if exists public.apply_prisma_state(text, smallint, smallint, smallint, smallint, smallint, text, text, integer, timestamptz, timestamptz, timestamptz, text, smallint, smallint, smallint, timestamptz, timestamptz);
drop function if exists public.apply_prisma_state(text, smallint, smallint, smallint, smallint, smallint, text, text, jsonb, integer, timestamptz, timestamptz, timestamptz, text, smallint, smallint, smallint, timestamptz, timestamptz);

create or replace function public.apply_prisma_state(
  p_discord_id text,
  p_familiarity smallint,
  p_warmth smallint,
  p_patience smallint,
  p_banter smallint,
  p_trust smallint,
  p_relationship_summary text,
  p_recent_milestones jsonb,
  p_interaction_count integer,
  p_summary_updated_at timestamptz,
  p_relationship_created_at timestamptz,
  p_relationship_updated_at timestamptz,
  p_mood text,
  p_energy smallint,
  p_sarcasm smallint,
  p_affection smallint,
  p_last_interaction_at timestamptz,
  p_temperament_updated_at timestamptz
)
returns void
language plpgsql
security definer
set search_path = pg_catalog
as $apply_prisma_state$
declare
  v_discord_id text := nullif(pg_catalog.btrim(p_discord_id), '');
begin
  if v_discord_id is null then
    raise exception 'p_discord_id nao pode ser vazio'
      using errcode = '22023';
  end if;

  insert into public.prisma_relationships (
    discord_id,
    familiarity,
    warmth,
    patience,
    banter,
    trust,
    relationship_summary,
    recent_milestones,
    interaction_count,
    summary_updated_at,
    created_at,
    updated_at
  ) values (
    v_discord_id,
    p_familiarity,
    p_warmth,
    p_patience,
    p_banter,
    p_trust,
    p_relationship_summary,
    p_recent_milestones,
    p_interaction_count,
    p_summary_updated_at,
    p_relationship_created_at,
    p_relationship_updated_at
  )
  on conflict (discord_id) do update set
    familiarity = excluded.familiarity,
    warmth = excluded.warmth,
    patience = excluded.patience,
    banter = excluded.banter,
    trust = excluded.trust,
    relationship_summary = excluded.relationship_summary,
    recent_milestones = excluded.recent_milestones,
    interaction_count = excluded.interaction_count,
    summary_updated_at = excluded.summary_updated_at,
    updated_at = excluded.updated_at;

  insert into public.prisma_emotional_states (
    user_id,
    mood,
    energy,
    sarcasm,
    affection,
    last_interaction_at,
    updated_at
  ) values (
    v_discord_id,
    p_mood,
    p_energy,
    p_sarcasm,
    p_affection,
    p_last_interaction_at,
    p_temperament_updated_at
  )
  on conflict (user_id) do update set
    mood = excluded.mood,
    energy = excluded.energy,
    sarcasm = excluded.sarcasm,
    affection = excluded.affection,
    last_interaction_at = excluded.last_interaction_at,
    updated_at = excluded.updated_at;
end
$apply_prisma_state$;

create or replace function public.reset_prisma_state(
  p_discord_id text,
  p_clear_history boolean default false
)
returns void
language plpgsql
security definer
set search_path = pg_catalog
as $reset_prisma_state$
declare
  v_discord_id text := nullif(pg_catalog.btrim(p_discord_id), '');
begin
  if v_discord_id is null then
    raise exception 'p_discord_id nao pode ser vazio'
      using errcode = '22023';
  end if;

  delete from public.prisma_relationships where discord_id = v_discord_id;
  delete from public.prisma_emotional_states where user_id = v_discord_id;
  if coalesce(p_clear_history, false) then
    delete from public.prisma_messages where user_id = v_discord_id;
  end if;
end
$reset_prisma_state$;

revoke all on function public.apply_prisma_state(text, smallint, smallint, smallint, smallint, smallint, text, jsonb, integer, timestamptz, timestamptz, timestamptz, text, smallint, smallint, smallint, timestamptz, timestamptz) from public, anon, authenticated;
revoke all on function public.reset_prisma_state(text, boolean) from public, anon, authenticated;
grant execute on function public.apply_prisma_state(text, smallint, smallint, smallint, smallint, smallint, text, jsonb, integer, timestamptz, timestamptz, timestamptz, text, smallint, smallint, smallint, timestamptz, timestamptz) to service_role;
grant execute on function public.reset_prisma_state(text, boolean) to service_role;

create or replace function public.consolidate_prisma_summaries(p_daily_before date, p_weekly_before date)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog
as $consolidate_prisma_summaries$
declare
  v_weekly integer := 0;
  v_monthly integer := 0;
begin
  if p_daily_before is null or p_weekly_before is null or p_weekly_before >= p_daily_before then
    raise exception 'Cortes de consolidacao invalidos' using errcode = '22023';
  end if;
  with weekly_source as (
    select d.user_id, d.summary_date, d.summary,
      date_trunc('week', d.summary_date::timestamp)::date as rollup_start
    from public.prisma_daily_summaries d
    where d.summary_date < p_daily_before
  ), weekly_rollup as (
    select user_id, rollup_start, rollup_start + 6 as rollup_end,
      left(string_agg(to_char(summary_date, 'YYYY-MM-DD') || ': ' || summary, E'\n' order by summary_date), 4000) as rollup_summary
    from weekly_source
    group by user_id, rollup_start
  )
  insert into public.prisma_period_summaries (user_id, period_type, period_start, period_end, summary, updated_at)
  select user_id, 'weekly', rollup_start, rollup_end, rollup_summary, now()
  from weekly_rollup
  on conflict (user_id, period_type, period_start) do update set
    summary = left(public.prisma_period_summaries.summary || E'\n' || excluded.summary, 4000),
    period_end = excluded.period_end,
    updated_at = excluded.updated_at;
  get diagnostics v_weekly = row_count;
  delete from public.prisma_daily_summaries where summary_date < p_daily_before;

  with monthly_source as (
    select p.user_id, p.period_start, p.summary,
      date_trunc('month', p.period_start::timestamp)::date as rollup_start
    from public.prisma_period_summaries p
    where p.period_type = 'weekly' and p.period_end < p_weekly_before
  ), monthly_rollup as (
    select user_id, rollup_start,
      (rollup_start + interval '1 month - 1 day')::date as rollup_end,
      left(string_agg(to_char(period_start, 'YYYY-MM-DD') || ': ' || summary, E'\n' order by period_start), 8000) as rollup_summary
    from monthly_source
    group by user_id, rollup_start
  )
  insert into public.prisma_period_summaries (user_id, period_type, period_start, period_end, summary, updated_at)
  select user_id, 'monthly', rollup_start, rollup_end, rollup_summary, now()
  from monthly_rollup
  on conflict (user_id, period_type, period_start) do update set
    summary = left(public.prisma_period_summaries.summary || E'\n' || excluded.summary, 8000),
    period_end = excluded.period_end,
    updated_at = excluded.updated_at;
  get diagnostics v_monthly = row_count;
  delete from public.prisma_period_summaries where period_type = 'weekly' and period_end < p_weekly_before;
  return jsonb_build_object('weekly_upserted', v_weekly, 'monthly_upserted', v_monthly);
end
$consolidate_prisma_summaries$;
revoke all on function public.consolidate_prisma_summaries(date, date) from public, anon, authenticated;
grant execute on function public.consolidate_prisma_summaries(date, date) to service_role;

create or replace function public.save_prisma_daily_summary(
  p_user_id text,
  p_summary_date date,
  p_summary text,
  p_message_ids text[]
)
returns integer
language plpgsql
security definer
set search_path = pg_catalog
as $save_prisma_daily_summary$
declare
  v_user_id text := nullif(pg_catalog.btrim(p_user_id), '');
  v_deleted integer := 0;
begin
  if v_user_id is null or p_summary_date is null or p_summary is null or char_length(pg_catalog.btrim(p_summary)) not between 3 and 1200 or coalesce(array_length(p_message_ids, 1), 0) = 0 then
    raise exception 'Parametros invalidos' using errcode = '22023';
  end if;
  insert into public.prisma_daily_summaries (user_id, summary_date, summary, updated_at)
  values (v_user_id, p_summary_date, pg_catalog.btrim(p_summary), now())
  on conflict (user_id, summary_date) do update set
    summary = right(public.prisma_daily_summaries.summary || E'\n' || excluded.summary, 1200),
    updated_at = excluded.updated_at;
  delete from public.prisma_messages
  where user_id = v_user_id and message_id = any(p_message_ids);
  get diagnostics v_deleted = row_count;
  return v_deleted;
end
$save_prisma_daily_summary$;

create or replace function public.enforce_prisma_retention(p_now timestamptz default now())
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog
as $enforce_prisma_retention$
declare
  v_weekly integer := 0;
  v_memories integer := 0;
  v_historical integer := 0;
begin
  if p_now is null then raise exception 'p_now nao pode ser nulo' using errcode = '22023'; end if;
  perform public.consolidate_prisma_summaries((p_now - interval '7 days')::date, (p_now - interval '90 days')::date);
  delete from public.ai_events where created_at < p_now - interval '24 hours';
  delete from public.ai_usage where created_at < p_now - interval '90 days';
  delete from public.prisma_period_summaries where period_type = 'monthly' and period_end < (p_now - interval '365 days')::date;
  get diagnostics v_weekly = row_count;
  update public.prisma_memories set status = 'forgotten', updated_at = p_now
  where status = 'active' and valid_until is not null and valid_until <= p_now;
  get diagnostics v_memories = row_count;
  delete from public.prisma_memories
  where (status = 'forgotten' and updated_at < p_now - interval '180 days')
     or (status = 'superseded' and updated_at < p_now - interval '365 days');
  get diagnostics v_historical = row_count;
  return jsonb_build_object('periods_deleted', v_weekly, 'memories_forgotten', v_memories, 'historical_memories_deleted', v_historical);
end
$enforce_prisma_retention$;

revoke all on function public.save_prisma_daily_summary(text, date, text, text[]) from public, anon, authenticated;
revoke all on function public.enforce_prisma_retention(timestamptz) from public, anon, authenticated;
grant execute on function public.save_prisma_daily_summary(text, date, text, text[]) to service_role;
grant execute on function public.enforce_prisma_retention(timestamptz) to service_role;

create or replace function public.delete_prisma_user_data(p_user_id text, p_scope text)
returns void
language plpgsql
security definer
set search_path = pg_catalog
as $delete_prisma_user_data$
declare
  v_user_id text := nullif(pg_catalog.btrim(p_user_id), '');
begin
  if v_user_id is null or p_scope not in ('history', 'memories', 'relationship', 'all') then
    raise exception 'Parâmetros inválidos' using errcode = '22023';
  end if;
  if p_scope in ('history', 'all') then delete from public.prisma_messages where user_id = v_user_id; end if;
  if p_scope in ('memories', 'all') then delete from public.prisma_memories where user_id = v_user_id; delete from public.prisma_user_profiles where user_id = v_user_id; delete from public.prisma_daily_summaries where user_id = v_user_id; delete from public.prisma_period_summaries where user_id = v_user_id; end if;
  if p_scope in ('relationship', 'all') then delete from public.prisma_relationships where discord_id = v_user_id; delete from public.prisma_emotional_states where user_id = v_user_id; end if;
end
$delete_prisma_user_data$;
revoke all on function public.delete_prisma_user_data(text, text) from public, anon, authenticated;
grant execute on function public.delete_prisma_user_data(text, text) to service_role;

-- preferred_style era uma segunda fonte para a mesma preferência. Em bancos
-- existentes, converte o valor em memória antes de remover a coluna antiga.
do $migrate_preferred_style$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'prisma_relationships' and column_name = 'preferred_style'
  ) then
    execute $sql$
      insert into public.prisma_memories (
        user_id, memory_key, memory_type, content, importance, confidence,
        occurrence_count, last_seen_at, created_at, updated_at
      )
      select discord_id, 'communication-style:inferred', 'communication',
        'Prefere respostas ' || trim(preferred_style) || '.', 62, 65, 1,
        coalesce(updated_at, now()), coalesce(created_at, now()), coalesce(updated_at, now())
      from public.prisma_relationships
      where nullif(trim(preferred_style), '') is not null
      on conflict (user_id, memory_key) where memory_key is not null and status = 'active' do update set
        content = excluded.content,
        importance = greatest(public.prisma_memories.importance, excluded.importance),
        confidence = greatest(public.prisma_memories.confidence, excluded.confidence),
        last_seen_at = greatest(public.prisma_memories.last_seen_at, excluded.last_seen_at),
        updated_at = greatest(public.prisma_memories.updated_at, excluded.updated_at)
    $sql$;
  end if;
end
$migrate_preferred_style$;
alter table public.prisma_relationships drop column if exists preferred_style;

-- Migra instalações anteriores para uma única linha de estado por pessoa.
insert into public.prisma_emotional_states (
  user_id, mood, energy, sarcasm, affection, last_interaction_at, updated_at
)
select discord_id, mood, energy, sarcasm, affection, last_interaction_at, updated_at
from public.prisma_temperament
on conflict (user_id) do update set
  mood = excluded.mood,
  sarcasm = excluded.sarcasm,
  last_interaction_at = excluded.last_interaction_at,
  updated_at = greatest(public.prisma_emotional_states.updated_at, excluded.updated_at);

drop table public.prisma_temperament;

commit;

notify pgrst, 'reload schema';

-- Não são criadas políticas públicas. O bot acessa as tabelas exclusivamente
-- pelo backend com SUPABASE_SECRET_KEY; nunca exponha essa chave ao Discord.
