create table if not exists public.user_settings (
  discord_id text primary key,
  nickname text not null default '',
  personality text not null default 'prisma_default',
  humor_level integer not null default 1 check (humor_level between 1 and 5),
  allow_mentions boolean not null default true,
  memory_enabled boolean not null default true,
  spontaneous_interactions boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.conversation_history (
  id bigint generated by default as identity primary key,
  discord_id text not null,
  channel_id text not null,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz not null default now()
);
create index if not exists conversation_history_user_created_idx on public.conversation_history (discord_id, created_at desc);
create index if not exists conversation_history_created_idx on public.conversation_history (created_at);

create table if not exists public.ai_usage (
  id bigint generated by default as identity primary key,
  discord_id text not null,
  model text not null,
  input_tokens integer not null default 0,
  output_tokens integer not null default 0,
  total_tokens integer not null default 0,
  estimated_cost_usd numeric(14,8) not null default 0,
  estimated_cost_brl numeric(14,8) not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists ai_usage_created_idx on public.ai_usage (created_at);

create table if not exists public.ai_events (
  id bigint generated by default as identity primary key,
  discord_id text not null,
  interaction_type text not null default 'spontaneous',
  created_at timestamptz not null default now()
);
create index if not exists ai_events_user_created_idx on public.ai_events (discord_id, created_at desc);

-- Migração compatível para instalações que usavam os nomes e a escala antigos.
update public.user_settings set personality = case personality
  when 'padrao' then 'prisma_default'
  when 'sarcastico' then 'sarcastic'
  when 'fofo' then 'cute'
  when 'caotico' then 'chaotic'
  else personality
end;
alter table public.user_settings alter column personality set default 'prisma_default';
alter table public.user_settings drop constraint if exists user_settings_humor_level_check;
update public.user_settings set humor_level = greatest(1, least(5, humor_level));
alter table public.user_settings add constraint user_settings_humor_level_check check (humor_level between 1 and 5);
alter table public.user_settings alter column humor_level set default 1;

alter table public.user_settings enable row level security;
alter table public.conversation_history enable row level security;
alter table public.ai_usage enable row level security;
alter table public.ai_events enable row level security;

notify pgrst, 'reload schema';

-- Não são criadas políticas públicas. O bot acessa as tabelas exclusivamente
-- pelo backend com SUPABASE_SECRET_KEY; nunca exponha essa chave ao Discord.
