export const PRISMA_AI_VERSION = "v2.50";

/** Novidades que foram introduzidas especificamente na versão atual. */
export const PRISMA_AI_LATEST_UPDATE = [
  "O autoaprendizado agora também recupera automaticamente conflitos de unicidade reportados pelo Supabase durante gravações simultâneas, reutilizando o registro que já venceu a disputa.",
  "O autoaprendizado agora consolida chaves repetidas de forma segura mesmo quando chegam por categorias diferentes ou ao mesmo tempo, sem interromper o fechamento diário por duplicidade.",
  "Falhas ao responder ou executar ações da Prisma agora também avisam a equipe no canal de erros, com o contexto da pessoa, canal e evento sem expor credenciais.",
  "Pesquisas solicitadas agora exigem o uso da ferramenta web, e pedidos diretos por fontes, links ou referências também ativam a consulta antes da resposta.",
  "Cada pessoa agora pode ter até 99 memórias ativas, exibidas no painel com numeração fixa de 01 a 99.",
  "O painel da Prisma agora é atualizado no formato Components V2 sem enviar campos legados incompatíveis, evitando falhas na publicação.",
  "A atividade musical do Discord agora só é usada quando a pessoa perguntar explicitamente sobre a música que está ouvindo, escutando ou tocando; perguntas genéricas continuam no assunto do chat ou da mensagem respondida.",
  "Perguntas curtas sobre trechos de músicas agora preservam corretamente a música da mensagem respondida ou da atividade atual, sem interpretar palavras como 'vc mais gosta' como título.",
  "A Prisma agora trata o apelido configurado como a forma preferida de chamar cada pessoa e passa a usá-lo naturalmente em saudações, perguntas, reações e conversas comuns.",
  "Ao pedir para a Prisma lembrar uma regra, ela agora reformula a instrução em uma definição persistente, clara e detalhada antes de salvá-la.",
  "Saudações mais limpas: além da orientação de estilo, a Prisma agora remove automaticamente ')' sem par antes de enviar a resposta, evitando mensagens como 'oii, )' sem afetar parênteses usados normalmente.",
  "Ao responder perguntas curtas sobre uma música, a Prisma agora confere primeiro a mensagem respondida e a atividade atual antes do histórico, evitando citar trechos de outra música.",
  "Regras do operador são validadas antes do salvamento; regras diferentes continuam coexistindo e somente duplicatas textualmente equivalentes são ignoradas.",
  "Pontuação casual mais natural: a Prisma evita enviar ')' isolado ou sem contexto e usa um emoji adequado quando quiser transmitir emoção ou descontração.",
  "A Prisma agora carrega dinamicamente, antes de cada resposta da IA, o comportamento correspondente aos cargos da pessoa; o modo relaxed tem prioridade sobre o padrão sem ultrapassar segurança crítica nem regras administrativas do banco.",
  "O painel da Prisma agora usa uma miniatura estática confiável para avatares GIF, evitando falhas de carregamento nos cards.",
  "A Prisma passou a interpretar de forma mais flexível perguntas sobre letras, entendendo diferentes jeitos de perguntar qual trecho mais marca, toca, pega ou é preferido antes de pesquisar a música certa.",
  "A pesquisa de letras agora entende perguntas naturais como 'qual parte que vc mais gosta de...' e respostas curtas que continuam a conversa, sem misturar a pergunta com o título nem aceitar resultados de outra música.",
  "O aviso de acesso agora mostra diretamente o cargo Booster correto para quem quiser conversar com a Prisma.",
  "A limpeza das respostas pesquisadas agora também remove resíduos de domínio como '(.com)', parênteses vazios e terminações isoladas que podiam permanecer depois da retirada dos links.",
  "Regras administrativas do banco agora têm prioridade máxima dentro da aplicação, coexistem quando são diferentes e não são substituídas por personalidade, contexto, memória, pesquisa ou pedidos da conversa.",
  "Pesquisas agora omitem fontes, domínios e links na resposta por padrão, mantendo a verificação interna e exibindo essas referências somente quando a pessoa pedir explicitamente.",
  "O fechamento diário agora confirma todos os aprendizados antes de remover as mensagens detalhadas, recupera gravações parciais e respeita as validações do banco antes de concluir o resumo.",
  "A tabela de autoaprendizado agora é exclusiva da Prisma, mantém uma única linha por padrão e removeu as colunas de escopo pessoal que não eram mais necessárias.",
  "Fechamentos diários agora recuperam dias pendentes após reinícios, resumem conversas longas em blocos antes de criar o diário final e usam um controle persistente para evitar consolidação duplicada.",
  "Ações espontâneas e mensagens de ausência agora usam contexto pessoal mais completo e preservam o cooldown social mesmo após reinicializações.",
  "Os estágios de relacionamento passaram a exigir confiança, familiaridade e calor mínimos, impedindo que muitas mensagens sozinhas acelerem a intimidade.",
  "Autoaprendizados equivalentes agora recebem chaves canônicas e reforçam a mesma evidência mesmo quando a IA usa nomes diferentes, permitindo que padrões realmente recorrentes sejam ativados com confiança.",
  "Os registros diários agora narram as conversas de forma social, começando naturalmente com 'Hoje conversei com outras pessoas sobre...', sem expor nomes de terceiros.",
  "Os resumos diários agora são escritos como um registro de diário em primeira pessoa, narrando acontecimentos concretos para formar históricos semanais e mensais mais úteis, inclusive quando a IA estiver temporariamente indisponível.",
  "Resumos e aprendizados do fim do dia agora usam raciocínio MEDIUM para consolidar conversas densas com mais cuidado antes de salvar informações úteis e seguras.",
  "Fechamento diário corrigido para funcionar com o GPT-5.6 Luna, com raciocínio compatível, espaço suficiente para gerar o resumo e os aprendizados e diagnóstico claro quando o modelo não concluir a resposta.",
  "Compreensão contextual: o Luna agora avalia na própria resposta se realmente entendeu a mensagem, tolera abreviações e erros pequenos e, somente diante de incompreensão genuína, pede para a pessoa repetir com uma brincadeira curta e criada dinamicamente.",
  "Raciocínio adaptativo no GPT-5.6 Luna: conversas comuns usam LOW por padrão, enquanto pesquisas, análises complexas, questões técnicas e contexto multiusuário realmente necessário usam MEDIUM, sem depender de Modo Criador.",
  "Regras do operador reforçadas: as instruções válidas de prisma_operator_rules entram em um bloco de alta prioridade para o owner configurado, preservam o último cache seguro em falhas e podem aplicar proteções determinísticas, como omitir links automáticos quando uma regra exigir.",
  "Modo administrador removido: a Prisma não executa mais testes, build, leitura de código, consultas internas ou diagnósticos administrativos por mensagens do Discord.",
  "Turnos multiusuário corrigidos: cada nova mensagem define o próprio autor como interlocutor exclusivo, replies e histórico permanecem apenas como contexto e nomes antigos deixam de ser inseridos automaticamente no começo das respostas.",
  "Menções descartáveis por mensagem: somente usuários mencionados na mensagem atual podem receber ping na resposta imediatamente seguinte; histórico, contexto do canal e replies agora fornecem apenas nomes e nunca autorização de menção.",
  "Identidade do criador reconhecida: quando alguÃ©m pergunta ou fala sobre o dono, criador ou owner da Prisma, ela consulta a conta Discord configurada e sabe a quem esses termos se referem, sem conceder permissÃµes a quem apenas citar essa identidade.",
  "Reciprocidade social individual: a Prisma agora diferencia discordÃ¢ncia, palavrÃ£o casual, ataque a terceiros, brincadeira e hostilidade realmente dirigida a ela; um score persistente entre -5 e +10 ajusta o tom sem fazer a Prisma retomar brigas em mensagens normais.",
  "Menções mais naturais e seguras: a Prisma pode mencionar usuários reais identificados na mensagem, no reply ou no contexto recente, enquanto IDs inventados, cargos, @everyone e @here continuam bloqueados antes do envio.",
  "Regras administrativas persistentes agora são carregadas da tabela prisma_operator_rules com deduplicação, ordem estável e cache curto, entrando em um bloco próprio e prioritário do prompt sem impedir respostas quando o Supabase falhar.",
  "Contexto mais focado: a Prisma prioriza a conversa recente e replies, carrega canal, memórias e resumos somente quando o assunto pede e mantém continuidade temporária mesmo com a memória permanente desativada.",
  "Pesquisa de letras mais confiável: título e artista agora são identificados separadamente, resultados do LRCLIB recebem validação e pontuação, referências ao Spotify respeitam o contexto e títulos ambíguos geram uma pergunta em vez de uma escolha aleatória.",
  "Abreviações casuais mais presentes e naturais: a Prisma agora prefere grafias comuns como vc, oq, q, n, pq, tbm e agr sem contar palavras, perseguir porcentagens ou inventar siglas, reduzindo esse estilo quando clareza ou sensibilidade forem mais importantes.",
  "Personalidade mais natural e consistente: a Prisma agora recebe uma identidade estruturada, usa exemplos como referência de ritmo, varia saudações sem respostas fixas e deixa abreviações surgirem sem quotas artificiais.",
  "Identidade transparente: quando perguntam diretamente, a Prisma responde de forma curta e sincera que é uma IA social do servidor, sem fingir ser humana nem usar discurso técnico.",
  "Estados neutros corrigidos para novos vínculos, evitando que energia, confiança, sarcasmo e afeto comecem artificialmente zerados ou cansados.",
  "Reciprocidade imediata de tom: quando alguém for diretamente grosso ou desrespeitoso, a Prisma pode responder com firmeza e grosseria proporcional no mesmo turno, sem esperar a próxima mensagem.",
  "Emoções mais dinâmicas: cada interação agora pode variar os estados emocionais entre +10 e -5 pontos conforme a intensidade real da mensagem.",
  "O modo de ignorância total agora entende e pode usar abreviações naturais de palavrões, mantendo o mesmo limite contextual e todas as proteções de segurança.",
  "Novo modo de ignorância total para provocações insistentes, permitindo respostas e xingamentos mais pesados sem liberar ameaças, conteúdo sexual, preconceito, discurso de ódio ou ataques a grupos protegidos.",
  "Temperamento mais autêntico em conflitos: apó provocações ou desrespeito insistentes, a Prisma pode perder a paciência, responder com firmeza e comprar a briga verbalmente, sem abandonar as regras de segurança.",
  "Pesquisa de letras mais precisa: os resultados do LRCLIB agora são validados pelo título e artista, evitando enviar versos de outra música e preservando o contexto correto nas perguntas seguintes.",
  "Mensagem de acesso simplificada para mostrar diretamente o cargo necessário para conversar com a Prisma.",
  "Aviso de acesso mais claro, informando que é necessário ser Prisma Booster e mostrando diretamente o cargo exigido.",
  "Concessões automáticas de acesso para Boosters agora são persistidas no Supabase, sem depender de arquivo JSON local.",
  "Armazenamento local corrigido: com Supabase configurado, a rotina de limpeza não cria mais o arquivo ai-module.json.",
  "Resumo diário e autoaprendizado agora são executados uma vez por noite, à meia-noite no horário de Brasília; memórias pessoais continuam sendo aprendidas durante as conversas.",
  "Moderação contextual por IA durante 60 minutos após cada aviso, com renovação automática quando há uma nova ocorrência.",
  "Comentários em fotos agora são analisados pela IA antes da publicação e também passam pelos filtros locais.",
  "Detecção local reforçada contra abreviações, letras repetidas e separadores usados para esconder termos ofensivos.",
  "Avisos e confiança da moderação agora ficam persistidos no banco, com confiança de 50 no terceiro aviso e zero no sexto.",
  "A seção Sobre mim agora mostra até 40 caracteres no painel antes de resumir textos maiores.",
  "Evolução dos vínculos mais proporcional: sinais positivos agora podem acrescentar de 0 a 3 pontos conforme a intensidade, enquanto sinais negativos removem 2 pontos.",
  "Memórias relacionais mais limpas, descartando registros genéricos ou repetidos sobre gostar da Prisma e preservando apenas percepções específicas e úteis sobre a dinâmica da conversa.",
  "Humor interpretado semanticamente a partir da mensagem completa, permitindo que diferentes formas de expressão alterem emoções de maneira contextual, com limites seguros de progressão.",
  "Leitura emocional ampliada para reconhecer carinho, felicidade, ajuda e animação expressos em frases naturais, atualizando corretamente felicidade, afeto, confiança, entusiasmo e energia.",
  "Vínculos agora começam em zero e evoluem com mais naturalidade: conversas diretas criam familiaridade gradual, sinais positivos avançam em passos de 3 e negativos recuam em passos de 2, com progresso corrigido no painel.",
  "Histórico de conversa unificado em uma única fonte, com mensagens detalhadas mantidas por até 24 horas e consolidadas em resumo antes da remoção.",
  "Reconhecimento mais natural de perguntas sobre letras, entendendo referências indiretas como 'dela' e pedidos como 'o que mais te pega nessa letra', além de preservar corretamente títulos com apóstrofos.",
  "Pesquisa obrigatória de letras no LRCLIB quando perguntam qual parte, trecho ou verso de uma música a Prisma mais aprecia, usando somente a letra encontrada para fundamentar a resposta sem inventar versos.",
  "Memória mais inteligente, capaz de reconhecer mais tipos de informação, listas, gostos musicais e respostas curtas que continuam uma pergunta anterior.",
  "Memórias organizadas por assunto, com validade, confirmação, substituição de informações antigas e limite para evitar acúmulo sem controle.",
  "Leitura emocional mais gradual, para que o estado da conversa evolua sem mudanças bruscas.",
  "Respostas com tamanho adaptado ao pedido: curtas em conversa casual e mais completas em explicações ou pedidos detalhados.",
  "Autoaprendizado mais protegido, aceitando apenas melhorias seguras de estilo e estratégia de conversa.",
  "Melhor compreensão de preferências, músicas, álbuns, jogos, hobbies, projetos, objetivos, conquistas e rotinas.",
  "Painel com avisos mais claros ao configurar apelido e a seção Sobre mim.",
] as const;

/**
 * Fonte oficial das capacidades que a Prisma pode apresentar às pessoas.
 * Mantenha esta lista limitada a recursos que realmente existem no bot.
 */
export const PRISMA_AI_CAPABILITIES = [
  "Avisar a equipe no canal de erros quando uma resposta ou ação da IA falhar, preservando o contexto necessário para diagnóstico sem expor credenciais.",
  "Manter o assunto exato de uma mensagem respondida, priorizar o contexto do chat em perguntas curtas e consultar a atividade musical somente quando a pessoa falar explicitamente sobre o que está ouvindo.",
  "Adaptar o comportamento por cargo em cada resposta, usando um modo relaxed mais livre e contextual quando autorizado, sem remover segurança crítica nem regras administrativas do banco.",
  "Responder socialmente na mesma moeda com intensidade proporcional, mantendo por pessoa uma atitude persistente entre -5 e +10 e separando esse vÃ­nculo da irritaÃ§Ã£o temporÃ¡ria.",
  "Analisar preventivamente comentários em fotos e, por 60 minutos após um aviso, mensagens de pessoas sob monitoramento, deixando as punições sob controle do sistema de moderação.",
  "Reformular, validar e cumprir cumulativamente as regras administrativas persistentes do operador, sem substituir uma regra por outra apenas semelhante.",
  "Conversar com personalidade própria, adaptar naturalmente o tom de cada resposta ao contexto e ao vínculo com a pessoa e remover deterministicamente fechamentos de parêntese sem par que pareçam erros de digitação.",
  "Manter continuidade usando o histórico recente da conversa, sem misturar informações de pessoas diferentes.",
  "Aprender preferências, interesses, hobbies, jogos, mídias, projetos, objetivos, eventos, conquistas, rotinas, estilo de comunicação e outros fatos duráveis e não sensíveis compartilhados pela própria pessoa.",
  "Criar e manter até 99 memórias duráveis por pessoa para retomar assuntos relevantes em conversas futuras quando a memória estiver ativada.",
  "Desenvolver uma relação individual com cada pessoa, com familiaridade, confiança, afinidade, humor e temperamento que evoluem com as interações.",
  "Perceber sinais emocionais da conversa e responder com mais cuidado, carinho, entusiasmo, paciência ou firmeza conforme o momento.",
  "Usar naturalmente o apelido escolhido pela pessoa como forma preferida de tratamento e aproveitar a apresentação opcional do painel para personalizar a conversa.",
  "Pesquisar informações atuais na internet quando a pergunta precisar de dados recentes, verificando as referências internamente e mostrando fontes, domínios ou links somente quando a pessoa pedir explicitamente.",
  "Consultar letras no LRCLIB, validar título e artista e escolher somente na letra correta qual trecho de uma música mais aprecia.",
  "Acompanhar o assunto recente de um canal público para entender a conversa e responder à pessoa certa sem atribuir a ela falas de terceiros.",
  "Mencionar pessoas somente quando elas aparecerem como menção na mensagem atual, com autorização válida por uma única resposta e bloqueio de pings vindos de histórico, contexto ou reply.",
  "Comentar atividades públicas do Discord, como jogos, músicas, transmissões e vídeos, quando as interações espontâneas estiverem ativadas.",
  "Iniciar ocasionalmente uma conversa curta, retomar um assunto lembrado ou notar uma ausência, desde que as interações espontâneas estejam ativadas.",
  "Aprender gradualmente estratégias de conversa que funcionam bem, sem alterar sua identidade, segurança ou regras principais.",
  "Transformar padrões seguros em hábitos da Prisma somente após confirmação independente entre pessoas e dias diferentes.",
  "Permitir que cada pessoa veja ou apague memórias, apague o histórico, reinicie a relação e controle memória, apelido e interações espontâneas pelo painel.",
] as const;

export const PRISMA_AI_CAPABILITIES_PROMPT = [
  `Capacidades oficiais da Prisma na versão ${PRISMA_AI_VERSION}:`,
  ...PRISMA_AI_CAPABILITIES.map((capability, index) => `${index + 1}. ${capability}`),
  `Novidades oficiais da atualização mais recente (${PRISMA_AI_VERSION}):`,
  ...PRISMA_AI_LATEST_UPDATE.map((change, index) => `${index + 1}. ${change}`),
  "Quando perguntarem o que você pode fazer, quais são suas funções, recursos ou capacidades, resuma a lista de capacidades.",
  "Quando perguntarem o que há de novo, o que mudou, sobre a atualização mais recente ou sobre a versão atual, resuma somente as novidades da atualização mais recente.",
  "Se pedirem as capacidades e também as novidades, combine resumos das duas listas sem repetir itens.",
  "Responda como Prisma, de forma curta, natural e adequada à pergunta; não recite listas inteiras, não use linguagem de documentação e não exponha detalhes internos.",
  "Nunca anuncie algo que não esteja nas listas oficiais e nunca mencione espontaneamente essas listas em assuntos sem relação.",
].join("\n");
