import { chmod, mkdir, readFile, rename, writeFile } from "node:fs/promises";
import path from "node:path";
import { createClient } from "@supabase/supabase-js";
import { config } from "../../config.js";

export type CustomCall = { id: string; guildId: string; ownerId: string; voiceChannelId: string; roleId: string; createdAt: string; updatedAt: string };
export type CustomCallMember = { id: string; customCallId: string; userId: string; addedAt: string };
export type CustomCallAccess = { guildId: string; userId: string; boosterAccess: boolean; manualAccess: boolean; createdAt: string; updatedAt: string };
type Database = { calls: CustomCall[]; members: CustomCallMember[]; access: CustomCallAccess[] };

const file = path.resolve(config.dataDir, "custom-calls.json");
const supabase = config.supabaseUrl && config.supabaseSecretKey
  ? createClient(config.supabaseUrl, config.supabaseSecretKey, { auth: { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false } })
  : null;
let queue = Promise.resolve();

const empty = (): Database => ({ calls: [], members: [], access: [] });
async function readLocal(): Promise<Database> { try { const parsed = JSON.parse(await readFile(file, "utf8")) as Partial<Database>; return { calls: parsed.calls ?? [], members: parsed.members ?? [], access: parsed.access ?? [] }; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return empty(); throw error; } }
async function writeLocal(db: Database): Promise<void> { await mkdir(path.dirname(file), { recursive: true }); const temp = `${file}.${process.pid}.tmp`; await writeFile(temp, JSON.stringify(db, null, 2), { encoding: "utf8", mode: 0o600 }); await rename(temp, file); await chmod(file, 0o600).catch(() => undefined); }
async function localMutation<T>(fn: (db: Database) => T | Promise<T>): Promise<T> { let resolve!: (value: T) => void, reject!: (reason?: unknown) => void; const result = new Promise<T>((ok, fail) => { resolve = ok; reject = fail; }); queue = queue.catch(() => undefined).then(async () => { try { const db = await readLocal(); const value = await fn(db); await writeLocal(db); resolve(value); } catch (error) { reject(error); } }); await queue; return result; }

function callFromRow(row: Record<string, unknown>): CustomCall { return { id: String(row.id), guildId: String(row.guild_id), ownerId: String(row.owner_id), voiceChannelId: String(row.voice_channel_id), roleId: String(row.role_id), createdAt: String(row.created_at), updatedAt: String(row.updated_at) }; }
function memberFromRow(row: Record<string, unknown>): CustomCallMember { return { id: String(row.id), customCallId: String(row.custom_call_id), userId: String(row.user_id), addedAt: String(row.added_at) }; }
function accessFromRow(row: Record<string, unknown>): CustomCallAccess { return { guildId: String(row.guild_id), userId: String(row.user_id), boosterAccess: row.booster_access === true, manualAccess: row.manual_access === true, createdAt: String(row.created_at), updatedAt: String(row.updated_at) }; }

export async function getCustomCall(guildId: string, ownerId: string): Promise<CustomCall | null> { if (!supabase) { await queue; return (await readLocal()).calls.find((item) => item.guildId === guildId && item.ownerId === ownerId) ?? null; } const { data, error } = await supabase.from("custom_calls").select("*").match({ guild_id: guildId, owner_id: ownerId }).maybeSingle(); if (error) throw new Error(error.message); return data ? callFromRow(data) : null; }
export async function saveCustomCall(call: CustomCall): Promise<void> { if (!supabase) { await localMutation((db) => { const index = db.calls.findIndex((item) => item.guildId === call.guildId && item.ownerId === call.ownerId); if (index >= 0) db.calls[index] = call; else db.calls.push(call); }); return; } const { error } = await supabase.from("custom_calls").upsert({ id: call.id, guild_id: call.guildId, owner_id: call.ownerId, voice_channel_id: call.voiceChannelId, role_id: call.roleId, created_at: call.createdAt, updated_at: call.updatedAt }, { onConflict: "guild_id,owner_id" }); if (error) throw new Error(error.message); }
export async function deleteCustomCallRecord(call: CustomCall): Promise<void> { if (!supabase) { await localMutation((db) => { db.calls = db.calls.filter((item) => item.id !== call.id); db.members = db.members.filter((item) => item.customCallId !== call.id); }); return; } const { error } = await supabase.from("custom_calls").delete().eq("id", call.id); if (error) throw new Error(error.message); }
export async function getCustomCallMembers(callId: string): Promise<CustomCallMember[]> { if (!supabase) { await queue; return (await readLocal()).members.filter((item) => item.customCallId === callId); } const { data, error } = await supabase.from("custom_call_members").select("*").eq("custom_call_id", callId).order("added_at"); if (error) throw new Error(error.message); return (data ?? []).map(memberFromRow); }
export async function addCustomCallMember(callId: string, userId: string): Promise<void> { const item = { id: crypto.randomUUID(), customCallId: callId, userId, addedAt: new Date().toISOString() }; if (!supabase) { await localMutation((db) => { if (!db.members.some((value) => value.customCallId === callId && value.userId === userId)) db.members.push(item); }); return; } const { error } = await supabase.from("custom_call_members").upsert({ id: item.id, custom_call_id: callId, user_id: userId, added_at: item.addedAt }, { onConflict: "custom_call_id,user_id", ignoreDuplicates: true }); if (error) throw new Error(error.message); }
export async function removeCustomCallMember(callId: string, userId: string): Promise<void> { if (!supabase) { await localMutation((db) => { db.members = db.members.filter((item) => item.customCallId !== callId || item.userId !== userId); }); return; } const { error } = await supabase.from("custom_call_members").delete().match({ custom_call_id: callId, user_id: userId }); if (error) throw new Error(error.message); }
export async function getCustomCallAccess(guildId: string, userId: string): Promise<CustomCallAccess | null> { if (!supabase) { await queue; return (await readLocal()).access.find((item) => item.guildId === guildId && item.userId === userId) ?? null; } const { data, error } = await supabase.from("custom_call_access").select("*").match({ guild_id: guildId, user_id: userId }).maybeSingle(); if (error) throw new Error(error.message); return data ? accessFromRow(data) : null; }
export async function setCustomCallAccess(guildId: string, userId: string, patch: Partial<Pick<CustomCallAccess, "boosterAccess" | "manualAccess">>): Promise<CustomCallAccess> { const current = await getCustomCallAccess(guildId, userId); const now = new Date().toISOString(); const next: CustomCallAccess = { guildId, userId, boosterAccess: patch.boosterAccess ?? current?.boosterAccess ?? false, manualAccess: patch.manualAccess ?? current?.manualAccess ?? false, createdAt: current?.createdAt ?? now, updatedAt: now }; if (!supabase) { await localMutation((db) => { const index = db.access.findIndex((item) => item.guildId === guildId && item.userId === userId); if (index >= 0) db.access[index] = next; else db.access.push(next); }); return next; } const { error } = await supabase.from("custom_call_access").upsert({ guild_id: guildId, user_id: userId, booster_access: next.boosterAccess, manual_access: next.manualAccess, created_at: next.createdAt, updated_at: next.updatedAt }, { onConflict: "guild_id,user_id" }); if (error) throw new Error(error.message); return next; }
