begin;

create table if not exists public.prisma_operator_rules (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  rule text not null check (char_length(rule) between 5 and 350),
  created_at timestamptz not null default now(),
  unique (owner_id, rule)
);

alter table public.prisma_operator_rules enable row level security;

commit;
