begin;

create table if not exists public.prisma_user_profiles (
  user_id text primary key,
  display_name text,
  profile_summary text,
  communication_style text,
  interests jsonb not null default '[]'::jsonb,
  known_preferences jsonb not null default '[]'::jsonb,
  first_interaction_at timestamptz not null default now(),
  last_interaction_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists prisma_user_profiles_last_interaction_idx
  on public.prisma_user_profiles (last_interaction_at desc);

create table if not exists public.prisma_memories (
  id bigint generated by default as identity primary key,
  user_id text not null,
  memory_type text not null check (memory_type in ('preference','interest','social','communication','event','project','relationship','inside_joke')),
  content text not null check (char_length(content) between 3 and 300),
  importance smallint not null default 50 check (importance between 0 and 100),
  confidence smallint not null default 60 check (confidence between 0 and 100),
  source_message_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists prisma_memories_user_idx on public.prisma_memories (user_id, updated_at desc);
create index if not exists prisma_memories_user_type_idx on public.prisma_memories (user_id, memory_type);
create unique index if not exists prisma_memories_user_content_uidx on public.prisma_memories (user_id, lower(content));

alter table public.prisma_user_profiles enable row level security;
alter table public.prisma_memories enable row level security;

commit;

notify pgrst, 'reload schema';
