begin;

create table if not exists public.prisma_messages (
  id bigint generated by default as identity primary key,
  message_id text not null unique,
  guild_id text not null,
  channel_id text not null,
  user_id text not null,
  content text not null,
  author_is_prisma boolean not null default false,
  reply_to_message_id text,
  created_at timestamptz not null default now()
);
create index if not exists prisma_messages_user_created_idx on public.prisma_messages (user_id, created_at desc);
create index if not exists prisma_messages_channel_created_idx on public.prisma_messages (channel_id, created_at desc);

alter table public.prisma_user_profiles
  add column if not exists guild_id text,
  add column if not exists created_at timestamptz not null default now();

create table if not exists public.prisma_daily_summaries (
  id bigint generated by default as identity primary key,
  user_id text not null,
  summary_date date not null,
  summary text not null check (char_length(summary) between 3 and 1200),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, summary_date)
);
create index if not exists prisma_daily_summaries_user_date_idx on public.prisma_daily_summaries (user_id, summary_date desc);

create table if not exists public.prisma_emotional_states (
  user_id text primary key,
  happiness smallint not null default 50 check (happiness between 0 and 100),
  sadness smallint not null default 0 check (sadness between 0 and 100),
  anger smallint not null default 0 check (anger between 0 and 100),
  irritation smallint not null default 0 check (irritation between 0 and 100),
  affection smallint not null default 30 check (affection between 0 and 100),
  curiosity smallint not null default 50 check (curiosity between 0 and 100),
  excitement smallint not null default 30 check (excitement between 0 and 100),
  boredom smallint not null default 0 check (boredom between 0 and 100),
  confidence smallint not null default 50 check (confidence between 0 and 100),
  energy smallint not null default 50 check (energy between 0 and 100),
  updated_at timestamptz not null default now()
);

alter table public.prisma_messages enable row level security;
alter table public.prisma_daily_summaries enable row level security;
alter table public.prisma_emotional_states enable row level security;

create or replace function public.delete_prisma_user_data(p_user_id text, p_scope text)
returns void
language plpgsql
security definer
set search_path = pg_catalog
as $delete_prisma_user_data$
declare
  v_user_id text := nullif(pg_catalog.btrim(p_user_id), '');
begin
  if v_user_id is null or p_scope not in ('history', 'memories', 'relationship', 'all') then
    raise exception 'Parâmetros inválidos' using errcode = '22023';
  end if;
  if p_scope in ('history', 'all') then
    delete from public.prisma_messages where user_id = v_user_id;
    delete from public.conversation_history where discord_id = v_user_id;
  end if;
  if p_scope in ('memories', 'all') then
    delete from public.prisma_memories where user_id = v_user_id;
    delete from public.prisma_user_profiles where user_id = v_user_id;
    delete from public.prisma_daily_summaries where user_id = v_user_id;
  end if;
  if p_scope in ('relationship', 'all') then
    delete from public.prisma_relationships where discord_id = v_user_id;
    delete from public.prisma_temperament where discord_id = v_user_id;
    delete from public.prisma_emotional_states where user_id = v_user_id;
  end if;
end
$delete_prisma_user_data$;

revoke all on function public.delete_prisma_user_data(text, text) from public, anon, authenticated;
grant execute on function public.delete_prisma_user_data(text, text) to service_role;

commit;

notify pgrst, 'reload schema';
