begin;

create table if not exists public.prisma_weekly_summaries (
  id bigint generated by default as identity primary key,
  user_id text not null,
  week_start date not null,
  week_end date not null,
  summary text not null check (char_length(summary) between 3 and 4000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, week_start),
  check (week_end = week_start + 6)
);
create index if not exists prisma_weekly_summaries_user_week_idx
  on public.prisma_weekly_summaries (user_id, week_end desc);

alter table public.prisma_weekly_summaries enable row level security;
revoke all on table public.prisma_weekly_summaries from anon, authenticated;
grant all on table public.prisma_weekly_summaries to service_role;
grant usage, select on all sequences in schema public to service_role;

create or replace function public.consolidate_prisma_daily_summaries(p_before date)
returns integer
language plpgsql
security definer
set search_path = pg_catalog
as $consolidate_prisma_daily_summaries$
declare
  v_count integer := 0;
begin
  if p_before is null then
    raise exception 'p_before nao pode ser nulo' using errcode = '22023';
  end if;
  insert into public.prisma_weekly_summaries (user_id, week_start, week_end, summary, updated_at)
  select user_id,
    date_trunc('week', summary_date::timestamp)::date as week_start,
    (date_trunc('week', summary_date::timestamp)::date + 6) as week_end,
    left(string_agg(to_char(summary_date, 'YYYY-MM-DD') || ': ' || summary, E'\n' order by summary_date), 4000),
    now()
  from public.prisma_daily_summaries
  where summary_date < p_before
  group by user_id, date_trunc('week', summary_date::timestamp)::date
  on conflict (user_id, week_start) do update set
    summary = left(public.prisma_weekly_summaries.summary || E'\n' || excluded.summary, 4000),
    week_end = excluded.week_end,
    updated_at = excluded.updated_at;
  get diagnostics v_count = row_count;
  delete from public.prisma_daily_summaries where summary_date < p_before;
  return v_count;
end
$consolidate_prisma_daily_summaries$;

create or replace function public.delete_prisma_user_data(p_user_id text, p_scope text)
returns void
language plpgsql
security definer
set search_path = pg_catalog
as $delete_prisma_user_data$
declare
  v_user_id text := nullif(pg_catalog.btrim(p_user_id), '');
begin
  if v_user_id is null or p_scope not in ('history', 'memories', 'relationship', 'all') then
    raise exception 'Parametros invalidos' using errcode = '22023';
  end if;
  if p_scope in ('history', 'all') then delete from public.prisma_messages where user_id = v_user_id; delete from public.conversation_history where discord_id = v_user_id; end if;
  if p_scope in ('memories', 'all') then delete from public.prisma_memories where user_id = v_user_id; delete from public.prisma_user_profiles where user_id = v_user_id; delete from public.prisma_daily_summaries where user_id = v_user_id; delete from public.prisma_weekly_summaries where user_id = v_user_id; end if;
  if p_scope in ('relationship', 'all') then delete from public.prisma_relationships where discord_id = v_user_id; delete from public.prisma_emotional_states where user_id = v_user_id; end if;
end
$delete_prisma_user_data$;

revoke all on function public.consolidate_prisma_daily_summaries(date) from public, anon, authenticated;
revoke all on function public.delete_prisma_user_data(text, text) from public, anon, authenticated;
grant execute on function public.consolidate_prisma_daily_summaries(date) to service_role;
grant execute on function public.delete_prisma_user_data(text, text) to service_role;

commit;

notify pgrst, 'reload schema';
