begin;

create table if not exists public.prisma_period_summaries (
  id bigint generated by default as identity primary key,
  user_id text not null,
  period_type text not null check (period_type in ('weekly','monthly')),
  period_start date not null,
  period_end date not null,
  summary text not null check (char_length(summary) between 3 and 8000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, period_type, period_start),
  check (period_end >= period_start)
);
create index if not exists prisma_period_summaries_user_end_idx on public.prisma_period_summaries (user_id, period_end desc);
create index if not exists prisma_period_summaries_type_end_idx on public.prisma_period_summaries (period_type, period_end);
alter table public.prisma_period_summaries enable row level security;
revoke all on table public.prisma_period_summaries from anon, authenticated;
grant all on table public.prisma_period_summaries to service_role;
grant usage, select on all sequences in schema public to service_role;

insert into public.prisma_period_summaries (user_id, period_type, period_start, period_end, summary, created_at, updated_at)
select user_id, 'weekly', week_start, week_end, summary, created_at, updated_at
from public.prisma_weekly_summaries
on conflict (user_id, period_type, period_start) do update set
  summary = excluded.summary, period_end = excluded.period_end, updated_at = excluded.updated_at;

drop function if exists public.enforce_prisma_retention(timestamptz);
drop function if exists public.consolidate_prisma_daily_summaries(date);
drop table public.prisma_weekly_summaries;

create or replace function public.consolidate_prisma_summaries(p_daily_before date, p_weekly_before date)
returns jsonb language plpgsql security definer set search_path = pg_catalog
as $consolidate_prisma_summaries$
declare v_weekly integer := 0; v_monthly integer := 0;
begin
  if p_daily_before is null or p_weekly_before is null or p_weekly_before >= p_daily_before then raise exception 'Cortes de consolidacao invalidos' using errcode = '22023'; end if;
  insert into public.prisma_period_summaries (user_id, period_type, period_start, period_end, summary, updated_at)
  select user_id, 'weekly', date_trunc('week', summary_date::timestamp)::date,
    (date_trunc('week', summary_date::timestamp)::date + 6),
    left(string_agg(to_char(summary_date, 'YYYY-MM-DD') || ': ' || summary, E'\n' order by summary_date), 4000), now()
  from public.prisma_daily_summaries where summary_date < p_daily_before
  group by user_id, date_trunc('week', summary_date::timestamp)::date
  on conflict (user_id, period_type, period_start) do update set
    summary = left(public.prisma_period_summaries.summary || E'\n' || excluded.summary, 4000), period_end = excluded.period_end, updated_at = excluded.updated_at;
  get diagnostics v_weekly = row_count;
  delete from public.prisma_daily_summaries where summary_date < p_daily_before;
  insert into public.prisma_period_summaries (user_id, period_type, period_start, period_end, summary, updated_at)
  select user_id, 'monthly', date_trunc('month', period_start::timestamp)::date,
    (date_trunc('month', period_start::timestamp) + interval '1 month - 1 day')::date,
    left(string_agg(to_char(period_start, 'YYYY-MM-DD') || ': ' || summary, E'\n' order by period_start), 8000), now()
  from public.prisma_period_summaries where period_type = 'weekly' and period_end < p_weekly_before
  group by user_id, date_trunc('month', period_start::timestamp)::date
  on conflict (user_id, period_type, period_start) do update set
    summary = left(public.prisma_period_summaries.summary || E'\n' || excluded.summary, 8000), period_end = excluded.period_end, updated_at = excluded.updated_at;
  get diagnostics v_monthly = row_count;
  delete from public.prisma_period_summaries where period_type = 'weekly' and period_end < p_weekly_before;
  return jsonb_build_object('weekly_upserted', v_weekly, 'monthly_upserted', v_monthly);
end
$consolidate_prisma_summaries$;

create or replace function public.enforce_prisma_retention(p_now timestamptz default now())
returns jsonb language plpgsql security definer set search_path = pg_catalog
as $enforce_prisma_retention$
declare v_history integer := 0; v_periods integer := 0; v_memories integer := 0;
begin
  if p_now is null then raise exception 'p_now nao pode ser nulo' using errcode = '22023'; end if;
  perform public.consolidate_prisma_summaries((p_now - interval '7 days')::date, (p_now - interval '90 days')::date);
  delete from public.conversation_history where created_at < p_now - interval '48 hours'; get diagnostics v_history = row_count;
  delete from public.ai_events where created_at < p_now - interval '48 hours';
  delete from public.ai_usage where created_at < p_now - interval '90 days';
  delete from public.prisma_period_summaries where period_type = 'monthly' and period_end < (p_now - interval '730 days')::date; get diagnostics v_periods = row_count;
  update public.prisma_memories set status = 'forgotten', updated_at = p_now where status = 'active' and valid_until is not null and valid_until <= p_now; get diagnostics v_memories = row_count;
  return jsonb_build_object('history_deleted', v_history, 'periods_deleted', v_periods, 'memories_forgotten', v_memories);
end
$enforce_prisma_retention$;

create or replace function public.delete_prisma_user_data(p_user_id text, p_scope text)
returns void language plpgsql security definer set search_path = pg_catalog
as $delete_prisma_user_data$
declare v_user_id text := nullif(pg_catalog.btrim(p_user_id), '');
begin
  if v_user_id is null or p_scope not in ('history', 'memories', 'relationship', 'all') then raise exception 'Parametros invalidos' using errcode = '22023'; end if;
  if p_scope in ('history', 'all') then delete from public.prisma_messages where user_id = v_user_id; delete from public.conversation_history where discord_id = v_user_id; end if;
  if p_scope in ('memories', 'all') then delete from public.prisma_memories where user_id = v_user_id; delete from public.prisma_user_profiles where user_id = v_user_id; delete from public.prisma_daily_summaries where user_id = v_user_id; delete from public.prisma_period_summaries where user_id = v_user_id; end if;
  if p_scope in ('relationship', 'all') then delete from public.prisma_relationships where discord_id = v_user_id; delete from public.prisma_emotional_states where user_id = v_user_id; end if;
end
$delete_prisma_user_data$;

revoke all on function public.consolidate_prisma_summaries(date, date) from public, anon, authenticated;
revoke all on function public.enforce_prisma_retention(timestamptz) from public, anon, authenticated;
revoke all on function public.delete_prisma_user_data(text, text) from public, anon, authenticated;
grant execute on function public.consolidate_prisma_summaries(date, date) to service_role;
grant execute on function public.enforce_prisma_retention(timestamptz) to service_role;
grant execute on function public.delete_prisma_user_data(text, text) to service_role;

commit;
notify pgrst, 'reload schema';
